steps:
  - block: ":red_button: Build and Publish"
    # branches: "main"

  - trigger: sdk-samples-build-publish-docker
    label: Build and Publish SWIFT
    build:
      message: '${BUILDKITE_MESSAGE}'
      commit: '${BUILDKITE_COMMIT}'
      branch: '${BUILDKITE_BRANCH}'
      env:
        APP_DIR: './server/swift/'
        DOCKER_TAG: 'swift-latest'

  - trigger: sdk-samples-build-publish-docker
    label: Build and Publish NODE
    build:
      message: '${BUILDKITE_MESSAGE}'
      commit: '${BUILDKITE_COMMIT}'
      branch: '${BUILDKITE_BRANCH}'
      env:
        APP_DIR: './server/node/'
        DOCKER_TAG: 'node-latest'
